import { PageLayout } from "@/components/layouts/page-layout";

export default function Terms() {
  return (
    <PageLayout>
      <div className="container py-12">
        <h1 className="text-4xl font-bold mb-8">
          Terms of Service
        </h1>
        <div className="prose dark:prose-invert max-w-none">
          <p>Last updated: {new Date().toLocaleDateString()}</p>

          <p>Welcome to FeedsGram! By using this bot, you agree to the following terms and conditions. These terms are designed to ensure a safe, efficient, and productive experience for all users. Please read them carefully before proceeding.</p>

          <h2>1. Purpose of the Bot</h2>
          <p>FeedsGram is developed to assist Telegram user administrators in managing their groups effectively. Its key features include:</p>
          <ul>
            <li>Moderating group chats by deleting unwanted messages and issuing warnings.</li>
            <li>Managing member permissions, such as muting, kicking, or banning users.</li>
            <li>Enforcing group-specific rules and regulations automatically.</li>
            <li>Sending alerts, notifications, or pre-configured responses to specific events.</li>
          </ul>

          <h2>2. User Responsibilities</h2>
          <p>By using this bot, you agree to the following responsibilities:</p>
          <ul>
            <li><strong>Compliance with Laws:</strong> You must adhere to all applicable local, national, and international laws as well as Telegram’s terms of service.</li>
            <li><strong>Proper Configuration:</strong> You are responsible for configuring and maintaining the bot’s settings according to your group’s requirements.</li>
            <li><strong>Prohibited Uses:</strong> The bot must not be used for any unlawful, harmful, or malicious purposes, including but not limited to:
              <ul>
                <li>a. Spreading spam or unsolicited content.</li>
                <li>b. Harassment, threats, or bullying of group members.</li>
                <li>c. Sharing illegal or offensive material.</li>
              </ul>
            </li>
          </ul>

          <h2>3. Data Collection and Usage</h2>
          <p>The bot collects limited data to function effectively. Here is what you need to know:</p>
          <ul>
            <li><strong>What Data is Collected:</strong> The bot may process data such as group activity logs, user IDs, and messages flagged for moderation.</li>
            <li><strong>Purpose of Data:</strong> The collected data is used strictly for executing bot commands, enforcing rules, and improving service functionality.</li>
            <li><strong>Data Privacy:</strong> No personal or sensitive information will be stored, shared, or used beyond what is necessary for the bot’s operation.</li>
            <li><strong>Log Usage:</strong> Any logs generated by the bot are for debugging and improving performance only.</li>
          </ul>

          <h2>4. Prohibited Activities</h2>
          <p>To maintain the bot’s integrity and ensure compliance, the following actions are strictly prohibited:</p>
          <ul>
            <li>Using the bot to share or promote offensive, harmful, or illegal content.</li>
            <li>Exploiting vulnerabilities in the bot or attempting unauthorized access to its systems.</li>
            <li>Impersonating the bot or misrepresenting its functions or purposes.</li>
          </ul>

          <h2>5. Bot Permissions</h2>
          <p>For optimal performance, the bot may require the following permissions:</p>
          <ul>
            <li><strong>Message Reading:</strong> The bot may need to read group messages for moderation purposes (only for actionable messages).</li>
            <li><strong>Message Deletion:</strong> It can delete inappropriate or flagged content.</li>
            <li><strong>Member Management:</strong> Actions such as muting, banning, or kicking members may be automated based on group rules.</li>
            <li><strong>Admin Rights:</strong> Some functionalities may require admin-level permissions in the group, such as editing settings or enforcing rules.</li>
          </ul>

          <h2>6. Liability and Disclaimer</h2>
          <ul>
            <li><strong>No Warranties:</strong> The bot is provided "as is" without warranties of any kind, either express or implied.</li>
            <li><strong>Limited Liability:</strong> The developers are not responsible for any damages arising from the bot’s use, including but not limited to:
              <ul>
                <li>a. Loss of data.</li>
                <li>b. Unintended bans or permissions errors.</li>
                <li>c. Any misuse of the bot by users.</li>
              </ul>
            </li>
            <li><strong>Testing:</strong> Users are encouraged to test the bot’s functionality in a controlled environment before deploying it extensively.</li>
          </ul>

          <h2>7. Termination of Access</h2>
          <p>The bot’s access to your group or its functionality may be terminated or restricted under the following conditions:</p>
          <ul>
            <li>If users violate these terms.</li>
            <li>If the bot is misused or its permissions are abused.</li>
            <li>Due to technical failures, maintenance, or operational challenges.</li>
          </ul>

          <h2>8. Updates and Changes to Terms</h2>
          <p>These terms may be updated periodically to reflect changes in the bot’s functionality, Telegram’s policies, or applicable laws. Users are encouraged to review these terms regularly to stay informed of any updates. Continued use of the bot after changes implies acceptance of the revised terms.</p>

          <h2>9. Support and Feedback</h2>
          <p>For technical support, feedback, or suggestions, please contact the developers at [Insert Contact Information]. Your input helps us improve and provide better service.</p>

          <p>By using FeedsGram, you confirm that you have read, understood, and agreed to these terms of usage. Thank you for choosing FeedsGram to assist with managing your Telegram groups effectively.</p>
        </div>
      </div>
    </PageLayout>
  );
}
